/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppCampaignsIdRouteImport } from './routes/app.campaigns_.$id'
import { Route as AppCampaignsNewRouteImport } from './routes/app.campaigns_.new'
import { Route as AppClientsIdRouteImport } from './routes/app.clients_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns_/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/campaigns_/new',
  path: '/campaigns/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients_/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/': typeof AppIndexRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/app/clients/$id': typeof AppClientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app': typeof AppIndexRoute
  '/app/campaigns/$id': typeof AppCampaignsIdRoute
  '/app/campaigns/new': typeof AppCampaignsNewRoute
  '/app/clients/$id': typeof AppClientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/': typeof AppIndexRoute
  '/app/campaigns_/$id': typeof AppCampaignsIdRoute
  '/app/campaigns_/new': typeof AppCampaignsNewRoute
  '/app/clients_/$id': typeof AppClientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/campaigns'
    | '/app/clients'
    | '/app/employees'
    | '/app/templates'
    | '/app/'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/clients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/campaigns'
    | '/app/clients'
    | '/app/employees'
    | '/app/templates'
    | '/app'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/clients/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/campaigns'
    | '/app/clients'
    | '/app/employees'
    | '/app/templates'
    | '/app/'
    | '/app/campaigns_/$id'
    | '/app/campaigns_/new'
    | '/app/clients_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns_/$id': {
      id: '/app/campaigns_/$id'
      path: '/campaigns/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campaigns_/new': {
      id: '/app/campaigns_/new'
      path: '/campaigns/new'
      fullPath: '/app/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients_/$id': {
      id: '/app/clients_/$id'
      path: '/clients/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppClientsRoute: typeof AppClientsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRoute,
  AppClientsRoute: AppClientsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppClientsIdRoute: AppClientsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
